function [BW,maskedImage,maskHigh] = segmentImageBrainDWI(data)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 28-Aug-2019
%----------------------------------------------------

%GS
X=data;

% Normalize input data to range in [0,1].
Xmin = min(X(:));
Xmax = max(X(:));
if isequal(Xmax,Xmin)
    X = 0*X;
else
    X = (X - Xmin) ./ (Xmax - Xmin);
end

%GS: get high-values (i.e. CSF) 
thr_high=0.4;
maskHigh=X>thr_high;

%GS: compress range
thr_comp=0.15;
X(X>thr_comp)=thr_comp;
X=X/thr_comp;


% Threshold image - global threshold
BW = imbinarize(X);

% Erode mask with disk
radius = 3;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Dilate mask with disk
radius = 10;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Active contour
iterations = 100;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Open mask with disk
radius = 9;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

